{
 "title": "PROYECTO1_ACE2_Modificado",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "camilla", "query": "SELECT id FROM Camilla;\n" }
  ]
 },
 "panels": [
  {
   "title": "Monitoreo Oxigeno",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT \n  sv.Fecha AS time,\n  sv.Oxigenacion AS \"Oxígeno (%)\"\nFROM \n  Signos_Vitales sv\nJOIN Diagnósticos d ON d.id = sv.Diagnósticos_id\nJOIN Pacientes p ON p.id = d.Pacientes_id\nJOIN Camilla c ON c.id = p.Camilla_id\nWHERE \n  $__timeFilter(sv.Fecha)\n  AND p.Camilla_id IN (${camilla:csv})\n  AND c.Estado = 'Ocupada'\nORDER BY \n  sv.Fecha;\n"
    }
   ]
  },
  {
   "title": "Frecuencia Cardiaca",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT \n  sv.Fecha AS time,\n  sv.Frecuencia_Cardiaca AS \"Frecuencia Cardíaca (bpm)\"\nFROM \n  Signos_Vitales sv\nJOIN Diagnósticos d ON d.id = sv.Diagnósticos_id\nJOIN Pacientes p ON p.id = d.Pacientes_id\nJOIN Camilla c ON c.id = p.Camilla_id\nWHERE \n  $__timeFilter(sv.Fecha)\n  AND p.Camilla_id IN (${camilla:csv})\n  AND TRIM(c.Estado) = 'Ocupada'\nORDER BY \n  sv.Fecha;\n"
    }
   ]
  },
  {
   "title": "Pacientes Ingresados",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT \n  p.Camilla_id AS Camilla,\n  MIN(sv.Oxigenacion) AS Min_Oxigenacion,\n  MAX(sv.Oxigenacion) AS Max_Oxigenacion,\n  AVG(sv.Oxigenacion) AS Prom_Oxigenacion,\n  MIN(sv.Frecuencia_Cardiaca) AS Min_ECG,\n  MAX(sv.Frecuencia_Cardiaca) AS Max_ECG,\n  AVG(sv.Frecuencia_Cardiaca) AS Prom_ECG\nFROM \n  Signos_Vitales sv\nJOIN Diagnósticos d ON d.id = sv.Diagnósticos_id\nJOIN Pacientes p ON p.id = d.Pacientes_id\nJOIN Camilla c ON c.id = p.Camilla_id\nWHERE \n  $__timeFilter(sv.Fecha)\n  AND p.Camilla_id IN (${camilla:csv})\n  AND c.Estado = 'Ocupada'\nGROUP BY \n  p.Camilla_id\nORDER BY \n  p.Camilla_id;\n"
    }
   ]
  },
  {
   "title": "Camillas Ocupadas",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT\n  c.id AS Camilla,\n  c.Estado,\n  c.Fecha AS \"Última actualización\",\n  p.Nombre_Completo AS \"Paciente asignado\"\nFROM\n  Camilla c\nLEFT JOIN\n  Pacientes p ON p.Camilla_id = c.id\nORDER BY\n  c.id;\n"
    }
   ]
  },
  {
   "title": "Porcentaje de ocupacion nivel 1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT \n  IF(Estado = 'Ocupada', 100, 0) AS \"Ocupación Nivel 1\"\nFROM Camilla\nWHERE id = 1;\n"
    }
   ]
  },
  {
   "title": "Porcentaje de ocupacion 2do nivel ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT \n  SUM(CASE \n        WHEN Estado = 'Ocupada' THEN 50 \n        ELSE 0 \n      END) AS \"Ocupación Nivel 2\"\nFROM Camilla\nWHERE id IN (2, 3);\n"
    }
   ]
  },
  {
   "title": "Alertas de Signos Vitales Críticos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "SELECT * FROM Signos_Vitales WHERE (Oxigenacion < 80 OR Frecuencia_Cardiaca > 120) ..."
    }
   ]
  },
  {
   "title": "Tiempo Promedio de Ocupación por Paciente",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT \n    MIN(Fecha) AS time,\n    AVG(DATEDIFF(Fecha_final, Fecha)) AS Promedio_Estadia\nFROM Pacientes\nWHERE Fecha IS NOT NULL AND Fecha_final IS NOT NULL\nGROUP BY YEAR(Fecha), MONTH(Fecha)\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Tendencia de Ingresos y Altas Médicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "ACYE2",
     "rawSql": "SELECT\n  DATE_FORMAT(Fecha, \n    CASE \n      WHEN '$intervalo' = 'day' THEN '%Y-%m-%d'\n      WHEN '$intervalo' = 'week' THEN CONCAT(YEAR(Fecha), '-W', WEEK(Fecha))\n      WHEN '$intervalo' = 'month' THEN '%Y-%m'\n    END\n  ) AS time,\n  Estado,\n  COUNT(*) AS cantidad\nFROM Pacientes\nWHERE $__timeFilter(Fecha)\n  AND Estado IN ('proceso', 'Alta')\nGROUP BY time, Estado\nORDER BY time ASC;\n"
    }
   ]
  }
 ]
}